# Generated by Django 5.0.1 on 2024-02-12 13:37

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='users/default.jpg', force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[200, 200], upload_to='users/images')),
                ('title', models.CharField(max_length=255)),
                ('blocks', models.CharField(max_length=255)),
            ],
        ),
    ]
